version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - ./data:/mosquitto/data/
    ports:
      - '1883:1883'

